# metaworld_stick-push.yaml을 가져와서 편집함

name: isaaclab_stack

task_name: ${name}

shape_meta: &shape_meta
  obs:
    point_cloud:
      shape: [2048, 6]
      type: point_cloud
    agent_pos:
      shape: [9]
      type: low_dim
  action:
    shape: [7]

env_runner:
  _target_: diffusion_policy_3d.env_runner.isaaclab_runner.IsaaclabRunner
  eval_episodes: 20
  max_steps: 400
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  n_envs: 1
  n_train: null
  n_test: null
  task_name: ${task_name}
  device: ${training.device}
  use_point_crop: ${policy.use_point_crop}

dataset:
  _target_: diffusion_policy_3d.dataset.isaaclab_dataset.IsaaclabDataset
  zarr_path: /workspace/isaaclab/scripts/imitation_learning/datasets/DP3/stack_image.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90


